name: Fazendo o deploy no S3 🤖

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fazendo o checkout
        uses: actions/checkout@v2

      - name: Configurando o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Instalando dependências
        run: npm install

      - name: Build da aplicação
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Deploy no S3
        run: aws s3 sync dist/my-portfolio/ s3://portfolio-guilherme
